stages:
  - trigger

trigger-a-job:
  stage: trigger
  variables: !reference [.a-api-common-variable, variables]
  rules:
    - !reference [.env-rules, rules]
  trigger:
    include: .trigger-gitlab-ci.yml

trigger-b-job:
  stage: trigger
  variables: !reference [.b-api-common-variable, variables]
  rules:
    - !reference [.env-rules, rules]
  trigger:
    include: .trigger-gitlab-ci.yml

include:
  - local: applications/.gitlab-ci.yml