.feature-rules:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(feature|fix|hotfix)[-\/][a-zA-Z0-9-]+$/
      changes:
        - applications/${PROJECT_NAME}/**/*
    - when: never

.develop-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - applications/${PROJECT_NAME}/**/*
    - when: never

.staging-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - applications/${PROJECT_NAME}/**/*
    - when: never

.prod-rules:
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $PROJECT_NAME && $CI_COMMIT_TAG =~ /^[\w]+-v[\d.]+$/
    - when: never

.env-rules:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(feature|fix|hotfix)[-\/][a-zA-Z0-9-]+$/
      changes:
        - applications/${PROJECT_NAME}/**/*
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - applications/${PROJECT_NAME}/**/*
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - applications/${PROJECT_NAME}/**/*
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $PROJECT_NAME && $CI_COMMIT_TAG =~ /^[\w]+-v[\d.]+$/

include:
  - local: applications/a-api/.gitlab-ci.yml
  - local: applications/b-api/.gitlab-ci.yml